- .travis.yml
- scripts/feature_toggle_report_generator.py
- scripts/tests/test_feature_toggle_report_generator.py
- templates/ida_base.tpl
- tox.ini
This makes a call to `code_annotations` to create the annotation docs for each IDA, and bundle them into their own sub-directory.
> generate annotation docs

- feature_toggle_annotations.yaml
There seems to be an unresolved discussion concerning which annotations should be used for feature toggles (https://github.com/edx/edx-toggles/pull/3). In favor of getting this tooling live, I have removed the `toggle_implementation` annotation from the configuration file, which unblocks the feature toggle report generator utility. Dev teams can reassess which annotations are needed once everything is in place.
> fix code annotation config file

- scripts/README.rst
- scripts/gather_feature_toggle_state.py
The gather feature toggle state job was failing because it couldn't connect to the right database. The read replica uses a different db name than devstack. This allows you to set an environment variable for the LMS (the only IDA used for now).
Re: https://openedx.atlassian.net/browse/DEVOPS-9326
> use env var to specify db name

- feature_toggle_annotations.yaml
Following a conversation with @robrap, I have changed the annotation token used to specify how a toggle is implemented from `.. toggle_type` to `.. toggle_implementation`. This follows the ideas set out in https://github.com/edx/edx-toggles/pull/3. I have also changed the  implementation types to be `CamelCase` instead of `separated_by_underscore`.
> change toggle_type to toggle_implementation

- scripts/README.rst
- scripts/feature_toggle_report_generator.py
Add a `click` flag to optionally publish the html report to Confluence, to make testing locally (and on Jenkins in the short-term) easier.
> add flag to optionally publish to confluence

- scripts/feature_toggle_report_generator.py
The `everyone` option on WaffleFlags hold precedence over the other options, and therefore I needed to adjust the state function accordingly. I also adjusted the display of the the flag to use the wording from the Django admin GUI.
> tweak waffle flag state logic for everyone option

- scripts/feature_toggle_report_generator.py
- scripts/tests/test_feature_toggle_report_generator.py
- templates/flag.tpl
`users` and `groups` were erroneously left out of both the computed flag `status` and the report. I have added them back in.
> add users and groups to waffle flag status and display

- .travis.yml
- CHANGELOG.rst
- docs/conf.py
- edx_toggles/__init__.py
- requirements/base.in
- setup.py
- tox.ini
this PR update tox and Travis configurations to 
- Add support for python 3.8
- drop support for Django versions older than 2.2
Relevant JIRA issue [here](https://openedx.atlassian.net/browse/BOM-1595).
> Added support for python 3.8 and dropped Django support for older versions

- CHANGELOG.rst
- scripts/feature_toggle_report_generator.py
- scripts/renderers.py
Also renamed it HtmlRenderer. This makes code easier to understand and gets dir
ready for a new renderer that outputs csv
This PR is part of refractoring scripts to get toggles data.
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
solutions, hacks, quick-and-dirty implementations, concerns about …
> [ARCHBOM-719] Moved Renderer to renderers.py

- scripts/feature_toggle_report_generator.py
- scripts/renderers.py
- scripts/toggles.py
CsvRenderer
- contains 2 functions: one to output WaffleFlag info csv, second to output Switch info csv
- the two are different cause Switch and WaffleFlag seem to have very different info, so it did not make sense for both to be in same csv. If we eventually decide to combine the reports, it should be easy to do
> Add V1 of a csv renderer for toggles report

- CHANGELOG.rst
- requirements/base.txt
- requirements/constraints.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/quality.txt
- requirements/scripts.txt
- requirements/test.txt
- requirements/travis.txt
- scripts/README.rst
- scripts/gather_feature_toggle_state.py
Also some cleanup in Changelog file.
**JIRA:** https://openedx.atlassian.net/browse/ARCHBOM-1364
1. Check out this branch
2. In devstack, add a course override at http://localhost:18000/admin/waffle_utils/waffleflagcourseoverridemodel/add/ with enabled=true, force on, flag=`foo.waffle.flag.bar`, course=`course-v1:edX+E2E-101+course`
3. Run `make feature-toggle-state` in provisioned devstack
4. Check output `feature-toggle-data/lms_waffle_utils.json`
Output should contain one record, like so:
```json
[
{
"model": "waffle_utils.waffleflagcourseoverridemodel",
"pk": 1,
"fields": {
"change_date": "2020-07-23T22:24:44.483Z",
"changed_by": 3,
"enabled": true,
"waffle_flag": "foo.waffle.flag.bar",
"course_id": "course-v1:edX+E2E-101+course",
"override_choice": "on"
}
} …
```
> Add output for waffle flag course overrides (ARCHBOM-1364)

- scripts/renderers.py
- scripts/tests/test_renderer.py
- scripts/toggles.py
Previously, I had prefixed data keys with either "annotation_" or "state_" to convey the source of data. This resulted in making the resulting csv reports very hard to read. Change to postfix "_a" and "_s" cause it should be less distracting. 
The alternative:
"a_" and "s_" prefix: I also considered this, but I think postfixes are better cause when quickly glancing through csv report, the key name is more important than its source.
> data keys now postfixed with either _a or _s

- scripts/feature_toggle_report_generator.py
- scripts/gather_feature_toggle_state.py
- scripts/ida_toggles.py
- scripts/tests/test_ida_toggles.py
- scripts/tests/test_toggles.py
- scripts/toggles.py
Note: You can see the updated reports in this build:
- https://tools-edx-jenkins.edx.org/job/Feature-Toggle-Report-Generator/job/publish-feature-toggle-report/100/
To get into the toggle state report, a CourseWaffleFlag
must have at least one of the following:
- waffle flag data
- course override data
- annotation data
Note: If a CourseWaffleFlag (in code), only has waffle
flag data, we will misreport it as a WaffleFlag until
it is annotated.
This commit adds fixes such that if the override data
or annotation data is found after the waffle flag data,
the toggle that was originally thought to be a WaffleFlag
should become a CourseWaffleFlag.
ARCHBOM-1392
finished.
> ARCHBOM-1392: fix CourseWaffleFlag issues

- CHANGELOG.rst
- docs/decisions/0003-django-setting-toggles.rst
Document decision to add a new utility
class for Django Setting feature toggles.
See 0003-django-setting-toggles.rst for
details.
ARCHBOM-1433
> ARCHBOM-1433: Draft ADR for DjangoSettingToggle

- CHANGELOG.rst
- docs/decisions/0003-django-setting-toggles.rst
* update to Accepted status.
* choose option 2 (from original ADR), SettingDictToggle, for 
implementing dicts.
* rename from DjangoSettingToggle to SettingToggle.
finished.
> update ADR for django setting toggles

- CHANGELOG.rst
- Makefile
- docs/decisions/0004-toggle-api.rst
- edx_toggles/__init__.py
- edx_toggles/tests/test_toggles.py
- edx_toggles/toggles/__init__.py
- edx_toggles/toggles/internal.py
- tests/test_models.py
- tox.ini
**Description:** This adds a `toggles` module to the edx_toggles package. We add there
classes to store feature toggles in django settings.
These classes expose an API that is similar to those of edx-platform's
waffle_utils, such that they can be added there without too many
changes.
**JIRA:** https://openedx.atlassian.net/wiki/spaces/COMM/pages/1596358943
**Dependencies:** a PR will have to be created in edx-platform to make use of this new feature
make test-django
**Reviewers:**
finished.
> [BD-21] Add setting toggles

- CHANGELOG.rst
- edx_toggles/__init__.py
- edx_toggles/tests/test_testutils.py
- edx_toggles/toggles/internal/waffle.py
- edx_toggles/toggles/testutils.py
**Description:** Backport `override_waffle_switch` from edx-platform. This utility function is used in edx-platform, but also in edx/completion.
**JIRA:** https://openedx.atlassian.net/wiki/spaces/COMM/pages/1596358943
**Merge deadline:** Before https://github.com/edx/edx-platform/pull/25417
**Reviewers:**
finished.
> [BD-21] Backport `override_waffle_switch` from edx-platform

- CHANGELOG.rst
- edx_toggles/__init__.py
- edx_toggles/tests/test_toggles.py
- edx_toggles/toggles/internal/waffle.py
**Description:** Fix waffle switch cache checking
**Dependencies:** edx-platform unit tests will fail when edx-toggles gets upgraded to 1.0.0.
**Reviewers:**
finished.
> [BD-21] Fix waffle switch cache checking

- scripts/ida_toggles.py
script was failing due to bad data input. Setting a default of ['unknown'] for case when toggle is missing data.
> Using get to set defult in dict lookup

- CHANGELOG.rst
- edx_toggles/__init__.py
- edx_toggles/toggles/__init__.py
We should watch for "edx_toggles.toggles.waffle.internal.legacy.WaffleSwitch"
custom attributes. Wherever those occur, we should replace:
from edx_toggles.toggles import WaffleFlag/WaffleSwitch
by:
from edx_toggles.toggles import LegacyWaffleFlag/LegacyWaffleSwitch
This will ensure forward compatibility with edx-toggles==2.0.0.
**Reviewers:**
finished.
> [BD-21] Improve monitoring of legacy Waffle class imports

- CHANGELOG.rst
- edx_toggles/__init__.py
- edx_toggles/toggles/__init__.py
- edx_toggles/toggles/internal/waffle/legacy.py
* Add ``deprecated_incompatible_legacy_waffle_class`` custom attribute
to any class (including subclasses), using the backward-incompatible
imports that will be removed in 2.0.0.
* Add ``deprecated_compatible_legacy_waffle_class`` custom attribute to
any class (including subclasses) using the legacy classes compatible
with 2.0.0 imports, but which should be removed in 3.0.0 (or some
future major version).
* Remove ``deprecated_edx_toggles_waffle`` custom attribute. In two
cases, it was replaced by the new ``*_legacy_waffle_class`` custom
attributes.  In one case, it was replaced with the already
existing and more appropriate ``deprecated_waffle_legacy_method`
custom attribute.
finished.
> enhance monitoring of legacy waffle classes

- CHANGELOG.rst
- edx_toggles/__init__.py
- edx_toggles/tests/test_testutils.py
- edx_toggles/tests/test_waffle.py
- edx_toggles/toggles/__future__.py
- edx_toggles/toggles/__init__.py
- edx_toggles/toggles/internal/waffle/legacy.py
**Description:** Deprecate WaffleFlagNamespace and WaffleSwitchNamespace. All related features and methods are displaced to the WaffleFlag/WaffleSwitch classes.
**Reviewers:**
finished.
This PR depends on https://github.com/edx/edx-toggles/pull/98
> [BD-21] Deprecate waffle namespaces

- CHANGELOG.rst
- edx_toggles/__init__.py
- edx_toggles/toggles/internal/waffle/__init__.py
- edx_toggles/toggles/internal/waffle/flag.py
- edx_toggles/toggles/internal/waffle/legacy.py
- edx_toggles/toggles/internal/waffle/switch.py
**Description:** We remove all references to the `WaffleFlag.set_monitor_value` method and the
WAFFLE_FLAG_CUSTOM_ATTRIBUTES setting, which is no longer used. This is done in a backward-compatible manner, such that existing calls to the `set_monitor_value` method can continue to exist.
**Merge deadline:** Feb 14 2021.
**Reviewers:**
finished.
> [BD-21] Stop monitoring WaffleFlag values

- CHANGELOG.rst
- scripts/toggles.py
**Description:** The toggle_type column used to be "SettingToggle" and "SettingDictToggle" for
these classes. It should instead be "django_settings".
**Merge deadline:** Feb 24 2021
**Reviewers:**
**Author concerns:** :warning: THIS CHANGE IS UNTESTED. I have no idea how to generate sample json/yml reports. The project README mentions that:
> Each IDA exposes an HTTP endpoint provided by the [TODO: pending] edx-toggles Django app. A scheduled job can use an OAuth client associated with a staff user to get a JWT, and then use the JWT against each configured IDA's toggle state endpoint.
Unfortunately I have not taken the time to perform these …
> Fix "toggle_type" column of Setting toggles in state report

- scripts/toggles.py
* add ConfigurationModels: Don't warn on ConfigurationModels, but count them as valid annotations.
* add module and class to summary: Add module and class state to summary view. These columns help make it simpler to reconcile unannotated state data without having to review the detail view.
> Enhance toggle report

- docs/how_to/documenting_new_feature_toggles.rst
**Description:** This PR fixes the reference link of `feature_toogle_annotations.yaml` file in `how_to` documentation.
**Merge deadline:** ASAP
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
> [FIX] feature_toogle_annotations.yaml reference link in how_to doc

- CHANGELOG.rst
- scripts/renderers.py
- scripts/tests/test_renderer.py
More detail in the comments but there was a corner case in our data
around the sorting key being explicitly set to None.  Handle that case
as if the sorting key is not set at all.
**Merge deadline:**  None
finished.
> fix: Handle None names annotation data.

- CHANGELOG.rst
- edx_toggles/__init__.py
- edx_toggles/tests/test_state.py
- edx_toggles/toggles/state/__init__.py
- edx_toggles/toggles/state/internal/report.py
This report, previously in edx-platform, could not be exposed in other IDAs.
Here, we expose the report with a simple API. The modular ToggleStateReport
class can be overridden such that custom toggle values (such as those coming
from edx-platform's WaffleFlagCourseOverrideModel) can be added to the report.
**Dependencies:** a corresponding PR will be opened on the edx-platform repo: https://github.com/edx/edx-platform/pull/26325
**Reviewers:**
finished.
> [BD-21] feat: expose toggle state report API

- docs/conf.py
- docs/how_to/documenting_new_feature_toggles.rst
- docs/how_to/implement_the_right_toggle_type.rst
- docs/index.rst
- edx_toggles/toggles/internal/waffle/__init__.py
fix: django package docs
The proper Django Settings were not getting used when building
docs, which caused certain modules to not build in the package
docs.
docs: update toggle documentation
* Enhance documenting_new_feature_toggles.rst.
* Add implement_the_right_toggle_type.rst.
Note: Some of the documentation ideas come from the [Docathon docs on Confluence](https://openedx.atlassian.net/wiki/spaces/AC/pages/2248409171/Toggles+and+Settings+Doc-a-thon+2021).
**Testing:**
* See this branch on readthedocs: https://draft-edx-toggles.readthedocs.io/en/latest/
* See the [broken production readthedocs for the state report module](https://edx.readthedocs.io/projects/edx-toggles/en/latest/edx_toggles.toggles.state.internal.html#edx-toggles-toggles-state-internal-report-module). …
> ARCHBOM-1721: docs: update toggle documentation

- docs/how_to/documenting_new_feature_toggles.rst
* Add github search url for doing research
* Minor updates to make optional annotations for apparent.
* Update additional resources with link to documenting non-boolean Django
settings.
See https://github.com/edx/code-annotations/pull/68 for how-to document a django setting, which we reference from this PR.
**JIRA:**
ARCHBOM-1721
> ARCHBOM-1721: docs: updates for feature toggle docs

- docs/how_to/documenting_new_feature_toggles.rst
docs: update how-to document toggles
* Add clarity around "temporary" use case.
* Add clarity for `toggle_target_removal_date` annotation.
* Add clarity for `toggle_tickets` annotation.
* Change based on [this forum discussion](https://discuss.openedx.org/t/discussion-regarding-adding-pull-requests-to-edx-toggle-annotations/4569/7). 
**JIRA:**
* [ARCHBOM-1743](https://openedx.atlassian.net/browse/ARCHBOM-1743)
* [ARCHBOM-1745](https://openedx.atlassian.net/browse/ARCHBOM-1745)
> ARCHBOM-1743/ARCHBOM-1745: docs: update how-to document toggles

- docs/how_to/adding_new_ida_to_toggle_report.rst
Update how-to report on new IDA
* Add help for documenting toggles on readthedocs.
* Move docs for setting up the Toggles State Endpoint, since this is
useful on its own.
* Separate a section for the how-to for configuring an IDA for the
Toggles Report Spreadsheet, from details on how the spreadhsheet is
produced.
**JIRA:**
ARCHBOM-1732
> ARCHBOM-1732: docs: update how-to report on new IDA

- edx_toggles/toggles/internal/waffle/flag.py
**Description:** This PR Update warning message when a request object is not available which could likely because of a context of a celery task.
**Reviewers:**
finished.
> Update warning message

- docs/how_to/implement_the_right_toggle_type.rst
`CourseWaffleFlag` org-level overrides were added in PR https://github.com/openedx/edx-platform/pull/29744 . This PR adds a mention of the new org-level override where the course-level override is currently mentioned in the documentation.
Work to add the org-level override counts to the toggle state report is underway - it will be completed in this ticket:
https://openedx.atlassian.net/browse/TNL-9513
**JIRA:**
https://openedx.atlassian.net/browse/TNL-8774
**Dependencies:** 
https://github.com/openedx/edx-platform/pull/29744
**Merge deadline:**
None
1. Read.
**Reviewers:**
finished.
**Author concerns:** 
None
> Add org-level overrides to CourseWaffleFlag docs.

- CHANGELOG.rst
- docs/how_to/documenting_new_feature_toggles.rst
Rename toggle_warnings to toggle_warning for consistency with setting_warning.
Relates to: https://github.com/openedx/code-annotations/pull/80
> FC-0001: rename toggle_warnings to toggle_warning

- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/pip-tools.txt
- requirements/pip.txt
- requirements/quality.txt
- requirements/scripts.txt
- requirements/test.txt
- Ran `make upgrade` locally to fix the issue with `pip` and `pip-tools` version conflict when running the requirements upgrade job through GitHub Actions.
> chore: upgrade python requirements

- requirements/base.txt
- requirements/ci.txt
- requirements/constraints.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/pip-tools.txt
- requirements/quality.txt
- requirements/scripts.txt
- requirements/test.txt
- `zip` constraint causing requirements upgrade [job](https://github.com/openedx/edx-toggles/actions/runs/3852261608/jobs/6564238268) to fail due to constraints conflict. 
- Removed the `zip` constraint which was added for `Python 3.5` support and is not needed anymore.
> fix: remove zip constraint

- requirements/base.txt
- requirements/ci.in
- requirements/ci.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/pip-tools.txt
- requirements/pip.txt
- requirements/quality.txt
- requirements/scripts.txt
- requirements/test.txt
- Codecov deprecated the pypi package long ago (Feb 2022) but left it up until now.
- Removing the package from requirements to fix the failing upgrade job.
- The Github Action we use to upload to codecov doesn't depend on the package so our CI coverage won't be affected by the change.
> fix: remove codecov package from requirements

- requirements/base.txt
- requirements/constraints.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/quality.txt
- requirements/scripts.txt
- requirements/test.txt
Remove all outdated dependency constraints.
Note: [Readthedocs builds are currently failing](https://readthedocs.org/projects/edx-toggles/builds/20898194/), and this should fix them.
> chore: remove outdated constraints

- .readthedocs.yaml
- docs/how_to/implement_the_right_toggle_type.rst
* fix: the readthedocs build
* docs: improve naming recommendations
Related to https://github.com/openedx/edx-platform/issues/33026
> Fix and improve toggle docs

- CHANGELOG.rst
- edx_toggles/tests/test_state.py
- edx_toggles/toggles/state/internal/report.py
Adds missing settings to the toggle report.
Fixes https://github.com/openedx/edx-toggles/issues/310
finished.
> fix: toggle report missing settings

- CHANGELOG.rst
- edx_toggles/tests/test_waffle.py
- edx_toggles/toggles/internal/waffle/base.py
Close #389.
@robrap is this what you had in mind in the issue you created? Crashing with a ValueError may be too radical. Do you think we should just log an error?
> fix: log error on waffle name with blank space

- README.rst
- catalog-info.yaml
- docs/how_to/adding_new_ida_to_toggle_report.rst
We migrated the edx-toggles documentation to docs.openedx.org, so update the URLs appropriately.
> docs: update edx.rtd links to docs.openedx.org

- scripts/configuration.yaml
**Description**
The [configuration.yaml] file only had LMS configuration but was missing CMS configuration, preventing the toggle annotation scripts from properly processing CMS feature toggles from the edx-platform repository.
**Fix:**
- `Added CMS configuration to the YAML file.`
This enables the annotation processing scripts to recognize and handle CMS as a separate IDA while pointing to the same edx-platform repository, completing the CMS integration for toggle reporting.
**Ticket**
https://2u-internal.atlassian.net/browse/BOM2-21
**Addition in Jenkins Job Script**
https://github.com/edx/jenkins-job-dsl-internal/pull/942
**Addition of cms configurations in feature-toggle-report-generator**
PR reference: https://github.com/edx/edx-internal/pull/13003
> fix: Add cms GitHub URL to configuration
