openedx/edx-toggles

- feature_toggle_annotations.yaml
Built off of https://github.com/edx/edx-toggles/pull/3 and mostly just tried addressing the comments and some small tweaks. This is certainly up for feedback or could be potentially changed in the future. Just wanted to get something started.
>  toggle annotations YAML

- scripts/feature_toggle_report_generator.py
Adding some logging to make debugging easier.
> add logging to the feature toggle report generator script

- README.rst
- scripts/README.rst
Add an example of a feature toggle annotation to the scripts README
> add an annotation example to readmes

- CHANGELOG.rst
- edx_toggles/__init__.py
- manage.py
- openedx.yaml
- pylintrc
- pylintrc_tweaks
- requirements/base.in
- requirements/base.txt
- requirements/constraints.txt
- requirements/dev.in
- requirements/dev.txt
- requirements/doc.in
- requirements/doc.txt
- requirements/pip-tools.in
- requirements/pip-tools.txt
- requirements/quality.in
- requirements/quality.txt
- requirements/scripts.txt
- requirements/test.in
- requirements/test.txt
- requirements/travis.in
- requirements/travis.txt
- setup.py
- tox.ini
https://openedx.atlassian.net/browse/BOM-1650
- Removed caniusepython3.
- upgraded all requirements.
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
> Removed caniusepython3 and upgraded all requirements.

- edx_toggles/__init__.py
- edx_toggles/apps.py
- edx_toggles/models.py
- edx_toggles/urls.py
- manage.py
- scripts/gather_feature_toggle_state.py
- setup.py
- test_settings.py
- tests/test_models.py
removed deprecated `__future__` imports
**JIRA:**
https://openedx.atlassian.net/browse/BOM-1723
finished.
> Removed deprecated future imports

- requirements/base.txt
- requirements/constraints.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/pip-tools.txt
- requirements/quality.txt
- requirements/scripts.in
- requirements/scripts.txt
- requirements/test.txt
- requirements/travis.txt
**Description:** This upgrades the dependencies to the latest supported versions under 3.5.
> Run make upgrade on this repo.

- feature_toggle_annotations.yaml
**Description:** Adds the `ExperimentWaffleFlag` as an option for waffle flags.
> Add ExperimentWaffleFlag as a possible type of waffle flag.

- scripts/feature_toggle_report_generator.py
- scripts/ida.py
- scripts/publish.py
- scripts/tests/test_feature_toggle_report_generator.py
- scripts/toggles.py
- templates/flag.tpl
- templates/switch.tpl
**Description:** Refactor script code into separate modules.
**JIRA:** https://openedx.atlassian.net/browse/ARCHBOM-1312
**Reviewers:**
> ARCHBOM-1312 - Refactor scripts to make it easier to write new renderers.

- scripts/README.rst
- scripts/feature_toggle_report_generator.py
- scripts/ida.py
- scripts/tests/test_feature_toggle_report_generator.py
**Description:** Some fixes and cleanup for the previous refactor.
**JIRA:** https://openedx.atlassian.net/browse/ARCHBOM-1311
> ARCHBOM-1311 - Refactoring cleanup and fixes.

- CHANGELOG.rst
- scripts/feature_toggle_report_generator.py
- scripts/ida_toggles.py
- scripts/renderers.py
- scripts/tests/test_ida.py
- scripts/tests/test_renderer.py
- scripts/toggles.py
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
> Adding course_override info to coursewaffleflags

- scripts/how_to/adding_new_ida_to_toggle_report.rst
Adding directions to add new IDA to automated toggle report generation.
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
> Adding how to

- CHANGELOG.rst
- docs/decisions/0001-purpose-of-this-repo.rst
- docs/decisions/0002-application-toggle-state.rst
- tox.ini
- ADR for why the overall repository exists
- ADR for creating an application endpoint for
toggle state
**JIRA:** 
ARCHBOM-1399
> ARCHBOM-1399: Add ADRs for repo and toggle state

- .github/PULL_REQUEST_TEMPLATE.md
- AUTHORS
- docs/decisions/0002-application-toggle-state.rst
minor updates to toggle state ADR
- fix bullets
- mention that the endpoint should require staff access.
Also, removed AUTHORS file.
**JIRA:**
ARCHBOM-1399
finished.
> ARCHBOM-1399: minor updates to toggle state ADR

- scripts/README.rst
**Description:** Refer to official docs for documenting feature toggles.
**JIRA:** BD-21: https://openedx.atlassian.net/wiki/spaces/COMM/pages/1596358943
**Reviewers:**
finished.~~
> [BD-21] Link to official feature toggle annotation docs in README

- scripts/feature_toggle_report.py
- scripts/ida_toggles.py
- scripts/renderers.py
- scripts/toggles.py
Previous refractoring of script had caused it to loss toggle_type info along the way. This adds in back and does some additional small fixes
> Fixing problems found during testing

- docs/decisions/0003-django-setting-toggles.rst
Now that the Setting Toggles have been implemented, update the ADR to say so.
> Update setting toggle ADR with implentation notes

- edx_toggles/toggles/internal/waffle/__init__.py
> fix: typo in docstring

- docs/how_to/adding_new_ida_to_toggle_report.rst
- docs/how_to/implement_the_right_toggle_type.rst
* Update how-to for reporting on an IDA with updates:
* We now have support for the toggle state endpoint.
* We now publish to a spreadsheet.
* Update how-to implement toggles, adding link to how-to
document toggles.
**JIRA:**
ARCHBOM-1746
> ARCHBOM-1746: docs: update toggle how-tos

- .github/workflows/ci.yml
- CHANGELOG.rst
- edx_toggles/__init__.py
- setup.py
- tox.ini
JIRA: https://openedx.atlassian.net/browse/BOM-2626
> feat: Added support for django3.2

- setup.py
This PR fixes an issue with the setup file classifiers that was introduced in (#188)
> Fix setup file issue

- docs/how_to/get_feature_toggles_annotation_data.rst
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
> docs: use the correct command example

- .github/workflows/ci.yml
- CHANGELOG.rst
- edx_toggles/__init__.py
- tox.ini
**Description:** Added support for Django 4.2
**Issue:** [Link to JIRA ticket](https://github.com/edx/upgrades/issues/155)
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
> fix: Added support for django 42

- edx_toggles/__init__.py
- tox.ini
instructions.
1. Open page A
2. Do thing B
**Reviewers:**
finished.
> fix: env 42 added

- .readthedocs.yaml
- docs/conf.py
See failing build: https://readthedocs.org/projects/edx-toggles/builds/27310903/
> build: fix doc.txt path in .rtd.yaml
